User can search for new pokemon
Nathan-Chon/ajax-project pull request #6
Opened 2023-03-01 23:07 UTC by Nathan-Chon

![image](https://user-images.githubusercontent.com/121650766/222287159-42da6806-bada-45d2-8aa9-382dc05d64cc.png)

2023-03-01 23:54 UTC, robgmerrill requested changes
Local storage key name update for project suggestion.

2023-03-01 23:54 UTC, robgmerrill commented on js/data.js
> +  localStorage.setItem('javascript-local-storage', formJSON);
Probably update this name from `'javascript-local-storage'` to `'party-local-storage'`

2023-03-01 23:54 UTC, robgmerrill commented on js/data.js
> +var dataInJSON = localStorage.getItem('javascript-local-storage');
Update `'javascript-local-storage'` to whatever name you use on line 9.

2023-03-02 00:07 UTC, Nathan-Chon commented
![animation47](https://user-images.githubusercontent.com/121650766/222295784-ec347ebe-568d-44f6-8cfd-16251cd197dd.gif)

2023-03-02 00:14 UTC, robgmerrill approved these changes
👍

2023-03-02 00:14 UTC, merged